rust-osdev/acpi

- src/lib.rs
- src/sdt.rs
This isn't ready yet, but the SDT checksum code has been bugging me and definitely isn't correct because it doesn't validate tables produced by `iasl` (the official compiler for ASL), so I decided to look into it properly.
ACPICA does this to calculate the checksum of a SDT:
``` c
UINT8
AcpiTbChecksum (
UINT8                   *Buffer,
UINT32                  Length)
{
UINT8                   Sum = 0;
UINT8                   *End = Buffer + Length;
while (Buffer < End)
{
Sum = (UINT8) (Sum + *(Buffer++));
}
return (Sum);
}
```
Now, this works because in C, unsigned integer overflow is defined like so (ISO/IEC 9899:2011 6.2.5.9):
> A computation involving unsigned operands can never overflow, because a result that cannot be represented by the resulting unsigned integer type is reduced …
> Checksums once and for all

- src/lib.rs
Line 80 of lib.rs: `accessibly by acpi` -> `accessible to the acpi crate`.
> Fix odd phrasing

- src/lib.rs
- src/rsdp.rs
- src/rsdp_search.rs
This adds a modified version of Flower's rsdp search (which works in qemu and on my lenovo laptop). It only works for bios machines (I believe UEFI gives you the location of the RSDP). It is untested as of yet, so please **do not merge it** (I will test it as soon as I can get flower's acpi crate branch working...).
It also appears that I have done something bad to the git history in my branch, so when it is merged please make sure to squash it.
TODO
> Add RSDP manual search

- src/aml/mod.rs
- src/aml/parser.rs
- src/fadt.rs
- src/interrupt.rs
- src/lib.rs
- src/madt.rs
- src/rsdp_search.rs
- src/sdt.rs
This starts adding support for the MADT
Thank you to @Sh4d1 for his initial work on this!
> Add support for the MADT

- acpi/Cargo.toml
- acpi/src/fadt.rs
- acpi/src/lib.rs
- acpi/src/sdt.rs
This makes accessing extended (and therefore only sometimes present) fields unsafe in the FADT. This abstraction is extendable to any other situations like this.
> Add ExtendedField abstraction

- README.md
- acpi/Cargo.toml
- acpi/src/lib.rs
- acpi/src/mcfg.rs
- acpi/src/sdt.rs
- aml_parser/Cargo.toml
This parses the MCFG SDT (I can't find what MCFG actually stands for, if anyone knows that'd be great), which describes the memory used by PCI-E configuration spaces. This PR parses the raw MCFG and constructs a nice interface type that is exposed to the library user. The main use of this type is through the `physical_address` method, that calculates the physical address of the start of the configuration region for a given PCI-E device.
Closes #43
> Parse the MCFG

- acpi/src/fadt.rs
- acpi/src/handler.rs
- acpi/src/hpet.rs
- acpi/src/lib.rs
- acpi/src/madt.rs
- acpi/src/mcfg.rs
- acpi/src/sdt.rs
- aml_parser/src/lib.rs
- aml_parser/src/misc.rs
- aml_parser/src/name_object.rs
- aml_parser/src/namespace.rs
- aml_parser/src/opcode.rs
- aml_parser/src/parser.rs
- aml_parser/src/pkg_length.rs
- aml_parser/src/term_object.rs
- aml_parser/src/test_utils.rs
- aml_parser/src/type1.rs
- aml_parser/src/type2.rs
- aml_parser/src/value.rs
- rustfmt.toml
Also includes some quick fixes.
Now that we can parse a sufficient subset of AML to parse a standard set of tables (QEMU's q35 DSDT and SSDTs), we can flesh out the parts of the parser that actually provide useful information to the OS.
Todo:
> [WIP] Make AML parser useful

- README.md
I noticed that the link to the ACPI specification was pointing to a specific version (6.2A) that is out of date. Changing the link to point to the UEFI web page where the latest version of the spec is posted. As of the date of this commit, the current version is 6.3. 
Kevin Shaw, Technical Writer, Intel Corporation
> Changing ACPI spec link to the web page with the latest version

- acpi/Cargo.toml
- acpi/src/fadt.rs
- acpi/src/hpet.rs
- acpi/src/lib.rs
- acpi/src/madt.rs
- acpi/src/mcfg.rs
- acpi/src/sdt.rs
- aml/Cargo.toml
- aml/src/parser.rs
- aml/src/term_object.rs
- aml/src/type2.rs
This upstreams a few assorted changes that I seem to have accumulated. Specifically:
* It removes the dependency on `typenum` (replacing them with const generics) to hopefully make `acpi` slightly smaller
* It makes accessing extended fields sound (I think it was unsound before, and just never seemed to miscompile), by treating them as uninitialised memory (instead of potentially treating them as initialised `()` types) until the version is checked
* It introduces a `Signature` type to represent SDT signatures
* It moves some AML opcode parsers around to be in the right place
Closes #44
> A few assorted changes

- acpi/Cargo.toml
- acpi/src/hpet.rs
- aml/Cargo.toml
- aml/src/name_object.rs
- aml/src/parser.rs
Fixes #66 
This should fix an error encountered if a `NameString` actually uses prefix chars (`^`). Also makes the fields of the `HpetInfo` struct public, which was requested on Gitter.
bors r+
> Parse prefix chars in NameStrings and make HPET fields public

- acpi/src/lib.rs
These features have now been stabilized.
> Remove two nightly features in the ACPI crate

- acpi/src/interrupt.rs
- acpi/src/madt.rs
The Bochs and VirtualBox emulators both seem to be missing the `LocalApicNmi` entry, which causes the `NoLocalNmiLineSpecified` error to be produced when parsing their tables.
I briefly looked at the ACPI specs. I'm not familiar at all with these specs, so I don't really know if this field is supposed to be mandatory or not. What the specs say, however, is that you can have multiple NMI lines.
Quoting section 5.2.12.7:
> Each Local APIC NMI connection requires a separate Local APIC NMI structure. For example, if the platform has 4 processors with ID 0-3 and NMI is connected LINT1 for processor 3 and 2, two Local APIC NMI entries would be needed in the MADT.
I therefore turned the `Option<_>` into a `Vec<_>`.
(Warning: I have no real clue what I'm doing. I'm not super familiar with ACPI in …
> Make local NMI line table optional

- acpi/Cargo.toml
- acpi/src/fadt.rs
- acpi/src/handler.rs
- acpi/src/interrupt.rs
- acpi/src/lib.rs
- acpi/src/madt.rs
- acpi/src/mcfg.rs
- acpi/src/rsdp_search.rs
- acpi/src/sdt.rs
The `acpi` crate is nearing the point where I'd like to get it stabilised and publish a `v1.0.0` version. This PR will make a few breaking changes for either correctness or future-proofing for the stuff that isn't yet implemented (e.g. the x2APIC) - I'd be interested in getting people's feedback on both the idea of stabilisation, and whether they think any other changes should be made to the crate before stabilisation.
Note that we're not stabilising the `aml` crate at this time.
cc @rust-osdev/acpi @64 @phil-opp
> Prepare for stabilisation of the `acpi` crate

- acpi/src/rsdp.rs
- aml/Cargo.toml
- aml/src/lib.rs
- aml/src/misc.rs
- aml/src/name_object.rs
- aml/src/namespace.rs
- aml/src/opcode.rs
- aml/src/parser.rs
- aml/src/pci_routing.rs
- aml/src/pkg_length.rs
- aml/src/term_object.rs
- aml/src/type1.rs
- aml/src/type2.rs
- aml/src/value.rs
- aml_tester/Cargo.toml
- aml_tester/src/main.rs
- rustfmt.toml
- tests/scopes.asl
This PR moves to a new representation of the namespace that stores values in a more efficient and, hopefully, also easier to query data structure. It also makes various changes to support this new representation.
cc @rust-osdev/acpi if anyone is interested, feel free to review / leave comments
> Move to new namespace representation

- acpi/src/lib.rs
- aml/src/lib.rs
- aml/src/name_object.rs
- aml/src/namespace.rs
- aml/src/opcode.rs
- aml/src/parser.rs
- aml/src/pci_routing.rs
- aml/src/pkg_length.rs
- aml/src/term_object.rs
- aml/src/test_utils.rs
- aml/src/type2.rs
- aml/src/value.rs
- aml_tester/src/main.rs
When a table is loaded, OSPM should traverse the namespace and call the `_INI` method on devices that need to perform device-specific initialization. Apparently lots of modern hardware will completely fail to work in ACPI mode if this is not done, so we should probably support it sooner rather than later.
Evaluating `_STA` and `_INI` on QEMU's tables seems to use a bunch of opcodes that we don't support yet, so this also builds a bunch more support for that.
Adds support for:
> Initialize objects and support all _STAs and _INIs on QEMU tables

- acpi/src/fadt.rs
- acpi/src/lib.rs
- acpi/src/platform/mod.rs
This PR introduces a new struct called `PmTimer`, which contains the information of the ACPI Power Management Timer. It can be constructed from `AcpiTables`.
> feat: add `PmTimer`

- aml/src/lib.rs
- aml/src/name_object.rs
- aml/src/namespace.rs
- aml/src/opcode.rs
- aml/src/parser.rs
- aml/src/pkg_length.rs
- aml/src/term_object.rs
- aml/src/test_utils.rs
- aml/src/type1.rs
- aml/src/type2.rs
- aml/src/value.rs
- aml_tester/src/main.rs
This PR makes the changes needed to allow AML methods to be defined natively (i.e. in Rust code, rather than in AML bytecode). This is useful for implementing methods such as `\_OSI`, but will also be useful in the future to allow method overrides for broken AML tables.
Allowing this change forces us to fix a couple of hacks we've been relying on, imposed by the fact that `AmlValue` (correctly) can no longer implement `PartialEq` or `Eq`. As values were previously stored in `AmlError`, predominantly to allow methods to return values (which were hackily propagated through the error system), this meant `AmlError` could also not be `Eq`, which would be inconvenient. Instead, we separate out the reasons to propagate a result using a new enum: `Propagate`. Getting here took a few attempts, but …
> Reorganise to allow native methods, then implement them

- aml/src/lib.rs
- aml/src/pci_routing.rs
- aml/src/resource.rs
- aml/src/value.rs
In a few places I wasn't able to figure out what the appropriate types to return in the error are, so I put `todo!()` instead of those values.
In a few other places I looked at what `AmlType` the `AmlValue` gets turned into here:
https://github.com/rust-osdev/acpi/blob/2fef29cb187dc944550b86ae978ae1620d7249e8/aml/src/value.rs#L227-L240
This made me wonder whether an `impl From<&AmlValue> for AmlType` would make sense. That would ensure that the conversion logic is in one place, instead of in multiple.
> Record attempted conversion in AmlError::IncompatibleValueConversion

- aml/src/lib.rs
- aml/src/value.rs
Before the introduction of native methods, the `AmlContext` structure was both `Send` and `Sync`, allowing it to be stored inside containers that require this.
For example, I store it in `spin::Once` to allow the global structure to be initialized once and shared, avoiding both complex data flow (e.g. across kernel tasks) and reparsing the AML many times.
To do this I made three changes:
1. The `Fn` for native methods in `MethodCode::Native` is now required to
be `Send` and `Sync`.
2. It now wraps the native function in an `alloc::sync::Arc` instead of `alloc::rc::Rc`.
3. The `Handler` trait requires implementations to implement `Send` and `Sync`.
> Regression: Ensure `AmlContext` is `Send` and `Sync` again.

- acpi/src/madt.rs
> Add Multiprocessor Wakeup structure

- aml/src/lib.rs
This pr adds a simple test to verify that `AmlContext` implements `Send + Sync`.
Closes #98
> Add test to verify that AmlContext implements Send and Sync

- acpi/Cargo.toml
- acpi/src/lib.rs
- rsdp/src/handler.rs
- rsdp/src/lib.rs
This pr makes `PhysicalMapping` sound:
- Previously one could safely construct a `PhysicalMapping` with `virtual_start` set to an invalid pointer and dereference it. This pr adds `PhysicalMapping::new` which is unsafe.
- `AcpiHandler::unmap_physical_region` no longer takes `self`. Implementations should use `PhysicalMapping::handler` to get the correct mapper. While it wasn't necessarily unsound to call `unmap_physical_region` on another `PhysicalMapper` removing `self` makes it's easier to implement `unmap_physical_region` safely.
This is a __breaking__ change.
> Fix physical mapping soundness

- rsdp/src/handler.rs
- rsdp/src/lib.rs
This pr implements `Send + Sync` for `PhysicalMapping` and add a test to check for those implementations.
> implement Send + Sync for PhysicalMapping

- acpi/src/fadt.rs
- acpi/src/lib.rs
- acpi/src/madt.rs
- acpi/src/mcfg.rs
- acpi/src/platform/mod.rs
- acpi/src/sdt.rs
- rsdp/src/lib.rs
- rustfmt.toml
Bit of a long title, but this has a breaking change (if I need to rebase, I can do that too, wouldn't be the first time :D). In short:
* This switches to using bitflags for flags in the `fadt` module
* This adds boot architecture and fixed feature flags as specified in tables 5.10-5.12 of [chapter 5 of ACPI 6.4](https://uefi.org/specs/ACPI/6.4/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html)
* This PR adds all the remaining signatures that are both reserved by ACPI and used by ACPI-defined tables as specified in tables 5.5-5.6 of the same chapter as above
In future I'm also planning to (possibly) define those tables. I also considered, but rejected for now, moving all the tables to a "tables" module for better organization; I've broken enough for this PR. :) …
> Add fixed flags and boot architecture flags; add extra table signatures as specified in tables 5.5 and 5.6 of ACPI 6.4

- acpi/src/lib.rs
To use this crate on stable Rust.
> chore(acpi): remove an unused feature gate

- aml/src/lib.rs
* This pull request re-exports all of the public items in the namespace
module. This is required for example in the `traverse` method it
requires the closure to take a namespace level which is private (not
exported) so, when we try to access the `typ` field on it, we are not
able to access it. The same applies for other methods in the `Namespace`
struct.
Signed-off-by: Andy-Python-Programmer <andypythonappdeveloper@gmail.com>
> Export all of the public items in namespace

- aml/src/pci_routing.rs
- aml/src/value.rs
I was trying to use `PciRoutingTable` module in my kernel with Bochs emulator. In the defalt configuration the PCI `_PTR` entries have `LinkObjects` refer to methods that return buffers ([Bochs bios asl source code](https://github.com/ipxe/bochs/blob/master/bios/acpi-dsdt.dsl)). The current code expects to have only buffers themselves in that position. This PR makes `PciRoutingTable::route` call the method instead of returning a conversion error, as [defined in the ACPI spec](https://uefi.org/specs/ACPI/6.4/06_Device_Configuration/Device_Configuration.html#crs-current-resource-settings).
> Make AML PciRoutingTable::route call LinkObject methods when required

- acpi/src/hpet.rs
This pr fixes the getter for the number of comparators for HPET.
>  The number in this field indicates the last timer (i.e. if there are three timers, the value will be 02h, four timers will be 03h, five timers will be 04h, etc.).
> (IA-PC HPET Specification)
> fix `HpetInfo::num_comparators`

- acpi/src/fadt.rs
- acpi/src/platform/interrupt.rs
- aml/src/lib.rs
This PR adjusts the construction of the `GenericAddress` for `pm_timer_block` to always check the `PM_TMR_LEN` value in the FADT. The ACPI spec indicates this value must be `4`, otherwise the PM_TMR isn't supported.
Additionally, `Clone, Copy, PartialEq, Eq` derive traits were added to `Polarity`, `LocalInterruptLine`, and `TriggerMode`.
Some comments, too.
> Various comments, fix `PM_TMR_BLK` checking of `PM_TMR_LEN` to match spec

- acpi/src/mcfg.rs
Improves the interface used by `PlatformInfo` to enumerate the PCIe configuration space. While the current enumeration via `PciConfig::physical_address` tends to be flexible enough for most implementations, a more involved implementation dealing with multi-socket or generally separated PCI host controllers (and so, dealing in separate segment groups) was not possible.
> Improve `PciConfigRegions` API

- aml_tester/Cargo.toml
- aml_tester/src/main.rs
Change to command line parsing to use clap 4 instead of clap 2. No change to behaviour is intended.
> Update aml_tester to clap 4

- aml_tester/src/main.rs
read_xx operations print a message and return 0. write_xx operations print a message and do nothing.
Strings are formatted with named parameters due to the number of parameters for PCI operations.
> Add stub implementations for Handler, read_u16 etc.

- aml/src/namespace.rs
- aml/src/opcode.rs
- aml/src/term_object.rs
`DEF_ALIAS_OP` added (0x06).
This implementation creates a new name in the namespace, but shares the handle with the target name. Any "namespace.get_..." will return the same object for both the alias and the target. The fact that the new name was declared as an alias is forgotten, and the fact that there is more than one name pointing to the same handle is forgotten. Support for an alias of a Scope/Level is not implemented and not checked.
> Add def_alias, alias shares handle with target

- aml/src/value.rs
There's a non-fatal compile error where a literal zero is specified as `0: u64` rather than `0u64`. This PR updates the syntax.
> Update syntax of literal zero

- acpi/Cargo.toml
- acpi/src/lib.rs
- acpi/src/sdt.rs
- rsdp/src/lib.rs
This is a collection of bugfixes and (backwards-compatible) improvements to the `acpi` and `rsdp` crates related to memory mapping. Descriptions of each change is provided in its commit message. Please let me know if I misinterpreted the code I modified or this pull request should be split up!
> acpi: Improve memory mapping usage

- aml/src/expression.rs
- aml/src/opcode.rs
Implemented `def_l_and` based on `def_l_or`. In order to test this on my DSDT, I needed functionality from the "Use `invoke_method`" PR, but I am not including any of that code here. This code has compiles as submitted.
> aml: Add l_and parser and opcode

- acpi/src/madt.rs
This adds the previously missing ['GICV'](https://uefi.org/specs/ACPI/6.5/05_ACPI_Software_Programming_Model.html?highlight=GICV#gic-cpu-interface-gicc-structure) field to `GiccEntry` (under the name `gic_virtual_registers_address`, renaming `gic_control_block_address` to `gic_hypervisor_registers_address` to match) and appends the two more recent 'SPE overflow Interrupt' and 'TRBE Interrupt' fields.
A question on appending fields that are introduced in later versions of the specification: Is it reasonable to be concerned about Rust implicitly accessing the new fields on a platform that does not provide them? I don't have an idea of the internals of the compiler, but it seems like the MADT entries might very well end at a page boundary and one risks accessing unmapped memory in the case …
> acpi: Add missing and new fields to GIC CPU interface structure

- aml/src/lib.rs
The unstable features `type_ascription` and `box_syntax` are not required to compile the `aml` crate. Additionally, `box_syntax` has been removed from rustc, so leaving it in will eventually cause an error.
> aml: Do not require unstable features from rustc that are not used

- aml_tester/src/main.rs
- `--path DIR` or positionals `FILE...` must be specified, but not both. Only one DIR is accepted at this time
- namespace is shared between tables by default, `--reset` to have a fresh namespace for each table
- files are processed in the order they are listed in the command line or directory, if an `aml` file and its `asl` source both appear in the list, the first occurrence will be taken as the intended sequence, repeated instances are ignored
- if `iasl` is missing, it is only reported after checking if anything needs to be compiled
> aml_tester: Add positional file arguments, in-order parsing and shared namespace

- aml/src/expression.rs
- aml/src/lib.rs
- aml/src/opcode.rs
- aml/src/term_object.rs
CondRefOf takes a source and an optional target, returning True if the source is defined. This first implementation only checks if the Reference source is defined. It will error if a target is given (new error code Unimplemented was added rather than using todo!() which will abort).
> AML: Add minimal CondRefOf support

- acpi/src/madt.rs
- acpi/src/mcfg.rs
In the absence of the allocator_api feature being enabled and/or other situtations it is useful to be able to access ACPI table fields directly.
This also allows the low-level use of the tables, especially when higher-level processing is not yet implemented.
Thus, this revision makes them and the Mcfg 'entries()' method public.
> acpi: Allow Madt and Mcfg fields to be accessed without allocator_api

- rsdp/src/lib.rs
Hi, I'm currently working on a bootloader and I need to be able to pass the RSDP to the operating system, so I added getters for more values.
> rsdp: Make whole RSDP readable

- rsdp/src/lib.rs
Since the memory mapping is already including "RSDP_V2_EXT_LENGTH" bytes to allow for an ACPI 1.0 table at the end of the region, it seems that the slice should just use the actual mapping length instead of going beyond it...
> acpi: fix length of "extended_area_bytes" in RSDP search

- aml/src/expression.rs
- aml/src/lib.rs
- aml/src/opcode.rs
- aml/src/value.rs
The PR implements `SizeOf (x)` operation for String, Buffer and Package types (the functionality for Object References isn't in place at the moment, so I marked it as `TODO`)
> AML: `DefSizeOf` implementation

- aml/src/expression.rs
- aml/src/term_object.rs
- aml/src/test_utils.rs
- aml/src/value.rs
This PR fixes the issue when entry count in DefPackage is less than NumElements specified by it:
```
// As found in the DSDT of Lenovo ThinkPad T430
...
Name (BT0P, Package (0x04){})
...
```
The spec says if NumElements is greater than the number of values provided, the rest should just be filled with an Uninitialized type value.
> AML: Fix DefPackage len < NumElements failing

- Cargo.toml
- README.md
- acpi/Cargo.toml
- acpi/src/handler.rs
- acpi/src/lib.rs
- acpi/src/managed_slice.rs
- acpi/src/mcfg.rs
- acpi/src/platform/mod.rs
- acpi/src/rsdp.rs
- rsdp/Cargo.toml
- rsdp/README.md
:warning: **This makes breaking changes to `acpi` , and so must not be merged without a major version bump** :warning: 
This PR prepares to publish a new version of `acpi`. Mainly, it tidies up the edges around the `allocator_api` feature by adding a new `alloc` feature that just uses the globally-set allocator; this will be the behaviour the majority of users want.
It's also an opportunity to round off any rough edges that only comes around occasionally, which is why it's taken so long for me to get around to. Apologies for the inordinately long time this has seemed to take though, everyone - it's one of those things that has slipped again and again, and now looks like an embarrassingly small diff.
That being said - if there's any changes anyone would like to see made before another …
> Prepare new version of `acpi`

- aml/src/expression.rs
- aml/src/opcode.rs
This PR implements some simple opcodes currently missing, but required for real-hardware function.
> aml: Implement DefOr, DefSubtract and DefLNot opcodes

- .github/workflows/build.yml
Closes #165 
Various people have been interested in using the library from targets other than `x86_64-*`, and so we should test builds against these targets in CI. This will probably take multiple goes to get right because Github Actions...
> Compile for aarch64 and i686 targets on CI in addition to x86_64

- acpi/src/madt.rs
`local_nmi_line_count` and `processor_count` must be increment if `MadtEntry::X2ApicNmi` and `MadtEntry::LocalX2Apic` are found. Otherwise, the index out of bounds panics will be invoked when accessing `local_apic_nmi_lines` and `application_processors`.
- https://github.com/rust-osdev/acpi/blob/baf55fe8a0530f8c84f9040d1f940ae3a0a7d993/acpi/src/madt.rs#L264
- https://github.com/rust-osdev/acpi/blob/baf55fe8a0530f8c84f9040d1f940ae3a0a7d993/acpi/src/madt.rs#L204
> fix: issue #200 increment `local_nmi_line_count` and `processor_count` on X2APIC

- acpi/src/handler.rs
Very simple change to get around the issue of derived impls requiring all type parameters to be `Debug`.
> Add `Debug` impl for `PhysicalMapping` even when `T` is not `Debug`

- acpi/src/lib.rs
This PR add `SdtHeaderIterator` to get all sdt headers.
> acpi: Add `SdtHeaderIterator` to get all headers.

- aml/src/lib.rs
- aml/src/test_utils.rs
Adds a more detailed error message that will print out the position in the buffer and a few bytes before and after the error.
Also fixes an unused argument warning in the test code.
> aml: add extra debug info on parsing error

- aml/src/expression.rs
- aml/src/statement.rs
- aml/src/value.rs
`if (field)` was seen in real-world AML. This change implements support for it.
> AML: implement boolean field

- aml/src/expression.rs
This PR replaces #209 - it is just a rebase, but I wanted to do it cleanly.
On my HP Laptop, Field is used as argument to ToInteger, even though the spec says it is not an option.
This is the declaration of VDID.
```
OperationRegion (RPXX, SystemMemory, GMIO (^_ADR, _ADR), 0x10)
1737E: 5B 80 52 50 58 58 00 47 4D 49 4F 5E 5F 41 44 52  // [.RPXX.GMIO^_ADR
1738E: 5F 41 44 52 0A 10                                // _ADR..
Field (RPXX, AnyAcc, NoLock, Preserve)
{
VDID,   32
}
17394: 5B 81 0B 52 50 58 58 00 56 44 49 44 20           // [..RPXX.VDID 
```
Here is where VDID is used in a Switch statement, causing the parser error.
```
Method (WIST, 0, Serialized)
{
173CD: 14 4A 14 57 49 53 54 08                          // .J.WIST.
173D5: 08 5F 54 5F 30 00                                // ._T_0. …
```
> AML: Allow Field in ToInteger (rebased)

- acpi/Cargo.toml
- acpi/src/address.rs
- acpi/src/lib.rs
- acpi/src/spcr.rs
Add support for the Serial Port Console Redirection (SPCR). The table provides information about the configuration and use of the serial port or non-legacy UART interface.
For more information, see:
<https://learn.microsoft.com/en-us/windows-hardware/drivers/serports/serial-port-console-redirection-table>
> acpi: add support for SPCR table

- aml_tester/src/main.rs
if args<=1 print help info, and add summary info
> aml_tester:Make cli print more pretty

- acpi/src/madt.rs
When parsing the interrupt model, including `MultiprocessorWakeup` in Madt will cause an error. We should ignore it.
> Ignore `MultiprocessorWakeup` when parse interrupt model

- acpi/src/lib.rs
> Add `from_rsdt` method for `AcpiTables`.

- acpi/src/handler.rs
- acpi/src/madt.rs
- acpi/src/platform/mod.rs
[ACPI specification r6.4](https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html#multiprocessor-wakeup-structure) introduced the Multiprocessor Wakeup Structure to let the bootstrap processor wake up application processors with a mailbox.
This PR follows the design and definition of ACPI specification and has been verified in my project.
> Implement the multiprocessor wakeup mechanism.

- acpi-dumper/src/main.rs
I got this error when running `cargo test` on a Mac host:
```
error[E0433]: failed to resolve: could not find `compilation_error` in `std`
--> acpi-dumper/src/main.rs:101:10
|
101 |     std::compilation_error!("acpi-dumper currently only supports linux");
|          ^^^^^^^^^^^^^^^^^ could not find `compilation_error` in `std`
```
This PR fixes the typo.
> acpi-dumper: fix invocation of compile_error!

- aml/src/resource.rs
The AML resource descriptor structs are useful in device initialization, however the fields of such structs, except `IrqDescriptor`, are private without any interface for accessing them. This commit makes those fields public.
Close #227
> aml: make resource descriptor fields public

- .github/workflows/build.yml
- acpi/src/handler.rs
- acpi/src/lib.rs
- acpi/src/madt.rs
- acpi/src/managed_slice.rs
- acpi/src/platform/mod.rs
* Fix several warnings so that clippy runs cleanly now.
* Add a clippy run on the acpi crate as part of CI.
> acpi: fix clippy warnings and run clippy in CI

- acpi/src/lib.rs
When generating the documentation, cargo doc would emit some warnings regarding redundant and broken links, so fix them. Also add some convenient links which were missing.
> acpi: fix doc warnings and add missing links

- acpi/src/spcr.rs
Change `SpcrInteraceType` to `SpcrInterfaceType`
> acpi: spcr: fix typo

- acpi/src/madt.rs
Copying and cloning a MADT does not copy Entries, so the cloned MADT is invalid.
But or maybe it's worth doing this: #223
> acpi: Remove Clone Copy traits for MADT

- acpi/src/managed_slice.rs
- acpi/src/platform/interrupt.rs
- acpi/src/platform/mod.rs
> acpi: Clone impl for PlatformInfo and ManagedSlice

- .github/workflows/build.yml
- aml/src/expression.rs
- aml/src/lib.rs
- aml/src/name_object.rs
- aml/src/namespace.rs
- aml/src/opregion.rs
- aml/src/parser.rs
- aml/src/pci_routing.rs
- aml/src/pkg_length.rs
- aml/src/resource.rs
- aml/src/statement.rs
- aml/src/term_object.rs
- aml/src/test_utils.rs
- aml/src/value.rs
* Fix several warnings so that clippy runs cleanly on the AML crate and its tests.
* Add clippy runs on the AML crate and its tests as part of CI.
* Add a missing clippy run on the ACPI crate tests.
> aml: fix clippy warnings and run clippy in CI

- acpi/src/handler.rs
- acpi/src/madt.rs
- acpi/src/platform/mod.rs
- acpi/src/sdt.rs
As reported in #218, we had a glaring soundness hole in the way we represented the MADT, which allowed an `Madt` to be moved away from its following entries. When `Madt::entries` was called, this would lead to arbitrary memory being read from after wherever the `Madt` ended up.
Moving the structures representing the tables is unlikely if the library is used as intended (and structures were `Copy` only because this was required by `repr(packed)`, but this is not actually required in the case of `Madt`), but this should obviously still be closed.
We make this sound by making `Madt: !Unpin`, which prevents the structure from being moved if in a `Pin`. To minimise difficulty using `PhysicalMapping`, we continue to allow mappings to deref to normal references if the underlying `T: Unpin`, but …
> Fix unsoundness in our representation of the MADT

- acpi/src/handler.rs
- acpi/src/madt.rs
- acpi/src/platform/mod.rs
This PR fixes build errors introduced in 8fa32488d635be56840ae976829279c08ce8548e and d4faad2fa6662f8abc2f89061066eb4eca7c3f8a.
> acpi: fix build errors
